[package]
name = "mac-notification-sys"
version = "0.1.0"
authors = ["Felix Döring <mail@felixdoering.com>"]
build = "build.rs"

[dependencies]
objc-foundation = "0.1.1"
chrono = "0.3.0"

[build-dependencies]
gcc = "0.3.43"
